name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8     
    - name: Prepare for build
      run: | 
        chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Cache Gradle
      uses: actions/cache@v1.0.0
      with:
        path: ~/.gradle/caches/
        key: ${{ runner.OS }}-gradle }}
        restore-keys: |
          ${{ runner.OS }}-gradle-${{ env.cache-name }}-
          ${{ runner.OS }}-gradle-
          ${{ runner.OS }}-
    - name: Cache Wrapper
      uses: actions/cache@v1.0.0
      with:
        path: ~/.gradle/wrapper/
        key: ${{ runner.OS }}-wrapper}}
        restore-keys: |
          ${{ runner.OS }}-wrapper-${{ env.cache-name }}-
          ${{ runner.OS }}-wrapper-
          ${{ runner.OS }}-
    - name: Cache build
      uses: actions/cache@v1.0.0
      with:
        path: ~/.android/build-cache
        key: ${{ runner.OS }}-build }}
        restore-keys: |
          ${{ runner.OS }}-build-${{ env.cache-name }}-
          ${{ runner.OS }}-build-
          ${{ runner.OS }}-
